# Generated by Django 4.1.5 on 2023-02-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userdata_managers_alter_userdata_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
