# Generated by Django 4.1.5 on 2023-03-13 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150)),
                ('map_link', models.CharField(max_length=200)),
                ('fives', models.BooleanField(default=False)),
                ('sevens', models.BooleanField(default=False)),
                ('elevens', models.BooleanField(default=False)),
                ('cricket', models.BooleanField(default=False)),
                ('cafe', models.BooleanField(default=False)),
                ('rest_room', models.BooleanField(default=False)),
                ('locker', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('turf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
