# Generated by Django 4.1.5 on 2023-03-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_turfdetails_image_alter_turfdetails_cafe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turfdetails',
            old_name='rest_room',
            new_name='first_aid',
        ),
    ]
