# Generated by Django 4.1.5 on 2023-03-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_rename_rest_room_turfdetails_first_aid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turfdetails',
            old_name='image',
            new_name='logo',
        ),
    ]
