# Generated by Django 4.1.5 on 2023-03-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0004_rename_image_turfdetails_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfdetails',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
