# Generated by Django 4.1.5 on 2023-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0009_remove_pricing_turf_turfdetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='court',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='price',
        ),
        migrations.AddField(
            model_name='pricing',
            name='cricket',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pricing',
            name='elevens',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pricing',
            name='fives',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pricing',
            name='sevens',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
