# Generated by Django 4.1.5 on 2023-04-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0011_reviewratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfdetails',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
