# Generated by Django 4.1.5 on 2023-05-01 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0012_turfdetails_unlisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.turfdetails')),
            ],
        ),
    ]
