# Generated by Django 4.1.5 on 2023-05-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0013_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='status',
            field=models.CharField(default='Ready to withdraw', max_length=100),
        ),
    ]
