# Generated by Django 4.1.5 on 2023-04-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookings_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='is_canceled',
        ),
    ]
